export const SELECTORS = {
  patientName: '[data-testid="patient-name"]',
  chiefComplaint: '[data-testid="chief-complaint"]',
  scriptedPhrase: '[data-testid="scripted-phrase"]',
  applyPhraseBtn: '[data-testid="apply-phrase-btn"]',
  createNoteBtn: '[data-testid="create-note-btn"]',
  notesList: '[data-testid="notes-list"]',
  noteItem: '[data-testid="note-item"]',
  noteComplaint: '[data-testid="note-complaint"]',
  checkboxCc: '[data-testid="checkbox-cc"]',
  checkboxAllergies: '[data-testid="checkbox-allergies"]',
  checkboxPain: '[data-testid="checkbox-pain"]',
  checkboxMeds: '[data-testid="checkbox-meds"]',
  checkboxConsent: '[data-testid="checkbox-consent"]',
};
